### ISSUE TITLE
PyMol not installed correctly?

### ISSUE THREAD

**Issue by RMeli** [brewsci/homebrew-bio#1343] opened 2021-04-23 20:20 UTC
A few weeks ago, I run `brew update` and a few days later I realized that `pymol` stopped working. Trying to uninstall and re-install did not work.

---

- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
   - Fixed most issues. The remaining issues are reported below:
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/rmeli/miniconda3/bin/icu-config
  /Users/rmeli/miniconda3/bin/xslt-config
  /Users/rmeli/miniconda3/bin/python3.7-config
  /Users/rmeli/miniconda3/bin/xml2-config
  /Users/rmeli/miniconda3/bin/python3.7m-config
  /Users/rmeli/miniconda3/bin/python3-config
  /Users/rmeli/miniconda3/bin/ncursesw6-config
  /Users/rmeli/miniconda3/bin/ncurses6-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ghostscript
```

- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

```
$ brew gist-logs pymol
Error: No logs.
```

- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config                                                                                                                             1 ↵
HOMEBREW_VERSION: 3.1.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: d89eda09abbeae907eb88bd6d01dc9cde7ff0e19
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6f487b915cea16858c541a6239cf1c550faf9012
Core tap last commit: 8 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.qY3M0R0nko/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

(For `brew doctor`, see above). 

To help us debug your issue please explain:

- What you were trying to do (and why)
 
I'm trying to install the open-source version of PyMol

- What happened (include command output)

```
$ brew reinstall pymol
==> Downloading https://ghcr.io/v2/brewsci/bio/pymol/manifests/2.4.0_3
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/e7a78742fad829743edd9341351051da5964a57fb9530685e2bae1235ccf5c24--pymol-2.4.0_3.bottle_manifest.json
==> Downloading https://ghcr.io/v2/brewsci/bio/pymol/blobs/sha256:1d910eb9d8ebe48d54f3ed62d4ff9ad1b94e7d8095f843f776938f0e53d2e5a5
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/2d7e45f7cd778c87fb5741d67cce4cc5c268d55e7a46fbb5fc85c3e66e1a3d96--pymol-2.4.0_3.catalina.bottle.tar.gz
==> Reinstalling brewsci/bio/pymol
==> Pouring pymol-2.4.0_3.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/pymol/2.4.0_3: 981 files, 21.5MB

$ pymol
Traceback (most recent call last):
  File "/usr/local/Cellar/pymol/2.4.0_3/libexec/lib/python3.9/site-packages/pymol/__init__.py", line 75, in <module>
    import pymol
  File "/usr/local/Cellar/pymol/2.4.0_3/libexec/lib/python3.9/site-packages/pymol/__init__.py", line 581, in <module>
    import pymol._cmd
ImportError: dlopen(/usr/local/Cellar/pymol/2.4.0_3/libexec/lib/python3.9/site-packages/pymol/_cmd.cpython-39-darwin.so, 2): Library not loaded: /usr/local/opt/netcdf/lib/libnetcdf.18.dylib
  Referenced from: /usr/local/Cellar/pymol/2.4.0_3/libexec/lib/python3.9/site-packages/pymol/_cmd.cpython-39-darwin.so
  Reason: image not found
```

- What you expected to happen

I expect `pymol` to work.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew install pymol
$ pymol
```

Happens on macOS `10.15.7`.

**Comment by aflaus** [comment] 2021-04-26 08:22
It appears that libnetcdf.18.dylib is being called explicitly but NetCDF has recently been updated to libnetcdf.19.dylib

The dynamic library call should really be to libnetcdf.dylib which is always symlinked to the latest version. Hopefully this can be fixed by the maintainer.

In the meantime, a workaround is to create a symlink from libnetcdf.18.dylib to libnetcdf.dylib:
`ln -s /usr/local/opt/netcdf/lib/libnetcdf.dylib /usr/local/opt/netcdf/lib/libnetcdf.18.dylib`

**Comment by YoshitakaMo** [comment] 2021-04-26 14:57
Thank you for your report, @RMeli and @aflaus. The cause and workaround described above are really correct.
I've updated the pymol bottle to keep up with the latest libnetcdf.

However, the component `_cmd.cpython-39-darwin.so` still depends on not only `libnetcdf.19.dylib` but also various numbered dynamic libraries.

``` 
$ otool -L /usr/local/Cellar/pymol/2.4.0_4/libexec/lib/python3.9/site-packages/pymol/_cmd.cpython-39-darwin.so

/usr/local/Cellar/pymol/2.4.0_4/libexec/lib/python3.9/site-packages/pymol/_cmd.cpython-39-darwin.so:
        /usr/local/opt/libpng/lib/libpng16.16.dylib (compatibility version 54.0.0, current version 54.0.0)
        /usr/local/opt/freetype/lib/libfreetype.6.dylib (compatibility version 24.0.0, current version 24.4.0)
        /usr/local/opt/libxml2/lib/libxml2.2.dylib (compatibility version 12.0.0, current version 12.10.0)
        /usr/local/opt/glew/lib/libGLEW.2.2.dylib (compatibility version 2.2.0, current version 2.2.0)
        /usr/local/opt/netcdf/lib/libnetcdf.19.dylib (compatibility version 19.0.0, current version 19.0.0)
        /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
        /System/Library/Frameworks/GLUT.framework/Versions/A/GLUT (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

I know `install_name_tool` command to modify the path of dynamic library for macOS, but I want to know how to do the same operation for Linux OS in a sophisticated way.

**Comment by aflaus** [comment] 2021-04-26 15:54
This is well beyond my level of knowledge, but would [patchelf](https://formulae.brew.sh/formula/patchelf) help?

**Comment by YoshitakaMo** [comment] 2021-04-30 06:43
The `patchelf` is a good tool. I'll try to use it next time.
Alternatively, there may be a way to change the rpath setting when compiling PyMOL. I'll look into this as well.

**Closed** 2021-04-30 06:44 UTC

**Comment by RMeli** [comment] 2021-04-30 07:36
Thanks @YoshitakaMo !
