### ISSUE TITLE
Install Pymol Failed on M1 MacBook Air (Big Sur 11.1)

### ISSUE THREAD

**Issue by perrogg** [brewsci/homebrew-bio#1290] opened 2021-02-21 14:49 UTC
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Tried to install pymol on M1 Mac (Big Sur 11.1) but failed.

I ran `brew update && brew install pymol`

- What happened (include command output)

# brew install brewsci/bio/pymol   output                                              
==> Installing pymol from brewsci/bio
==> Downloading https://files.pythonhosted.org/packages/13/ea/c6a302ccdfdcc1ab200bd2b7561e574329055d2974b1fb7939a7aa374da3/mmtf
Already downloaded: /Users/liulijun/Library/Caches/Homebrew/downloads/8184cd2975ddc6f5276f8aca6273b4b0e2e98a69ae60a94e8f087e2bf4f7fbc2--mmtf-python-1.1.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/81/9c/0036c66234482044070836cc622266839e2412f8108849ab0bfdeaab8578/msgp
Already downloaded: /Users/liulijun/Library/Caches/Homebrew/downloads/432b50d5f899f052d91eb12c17bb4fe7686828cd77a7f5d3b6e4f646b09eabf6--msgpack-0.6.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/8a/20/6eca772d1a5830336f84aca1d8198e5a3f4715cd1c7fc36d3cc7f7185091/msgp
Already downloaded: /Users/liulijun/Library/Caches/Homebrew/downloads/49c4120b43aa86620eaebc552b359f6d897f72f59d979634a803f54088ea44d8--msgpack-python-0.5.6.tar.gz
==> Downloading https://files.pythonhosted.org/packages/73/0c/55e4294143ba6781936c799ff13181db9109b161a8d8fc9b50eec45e1134/msgp
Already downloaded: /Users/liulijun/Library/Caches/Homebrew/downloads/cc8ecf250035cd7b706c464cf5a1be6cfdd1a92482350d209d6900918ec93b34--msgpack-tool-0.0.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/e7/20/8d0c4ba96a5fe62e1bcf2b8a212ccfecd67ad951e8f3e89cf147d63952aa/Pmw-
Already downloaded: /Users/liulijun/Library/Caches/Homebrew/downloads/50fbcfa2c8f747eb0d10f58fb92b1405935cdbeb84b675b4a28b0235409fa10b--Pmw-2.0.1.tar.gz
==> Downloading https://github.com/schrodinger/pymol-open-source/archive/v2.4.0.tar.gz
Already downloaded: /Users/liulijun/Library/Caches/Homebrew/downloads/979041808e9e071a298812894dbbc30631452979e67b242ae6214aa28871ed22--pymol-open-source-2.4.0.tar.gz
==> /opt/homebrew/opt/python@3.9/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/opt/homebrew/Cellar/pymol/
==> /opt/homebrew/opt/python@3.9/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/opt/homebrew/Cellar/pymol/
==> /opt/homebrew/opt/python@3.9/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/opt/homebrew/Cellar/pymol/
==> /opt/homebrew/opt/python@3.9/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/opt/homebrew/Cellar/pymol/
==> /opt/homebrew/opt/python@3.9/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/opt/homebrew/Cellar/pymol/
==> /opt/homebrew/opt/python@3.9/bin/python3 setup.py install --install-scripts=/opt/homebrew/Cellar/pymol/2.4.0/libexec/bin --
Last 15 lines from /Users/liulijun/Library/Logs/Homebrew/pymol/06.python3:
layer0/os_gl_glut_real.h:87:36: note: expanded from macro 'p_glutMainLoop'
#define p_glutMainLoop             glutMainLoop
                                   ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/GLUT.framework/Headers/glut.h:438:22: note: 'glutMainLoop' has been explicitly marked deprecated here
extern void APIENTRY glutMainLoop(void) OPENGL_DEPRECATED(10_0, 10_9);
                     ^
clang++ -I/opt/homebrew/opt/freetype/include -std=c++11 -D_PYMOL_LIBPNG -D_PYMOL_FREETYPE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -DMMTF_MSGPACK_USE_CPP11 -D_PYMOL_CTEST -D_PYMOL_OSX -D_PYMOL_NUMPY -Iinclude -Icontrib/uiuc/plugins/include -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Imodules/cealign/src -Ibuild/generated -Icontrib/uiuc/plugins/molfile_plugin/src -Icontrib/mmtf-c -IlayerCTest -I/opt/homebrew/lib/python3.9/site-packages/numpy/core/include -I/opt/homebrew/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c -MMD ov/src/OVContext.cpp -o build/temp.macosx-11-arm64-3.9/ov/src/OVContext.o -Werror=return-type -Wunused-variable -Wno-switch -Wno-narrowing -Wno-char-subscripts -O3 -fno-strict-aliasing
79 warnings generated.
clang++ -I/opt/homebrew/opt/freetype/include -std=c++11 -D_PYMOL_LIBPNG -D_PYMOL_FREETYPE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -DMMTF_MSGPACK_USE_CPP11 -D_PYMOL_CTEST -D_PYMOL_OSX -D_PYMOL_NUMPY -Iinclude -Icontrib/uiuc/plugins/include -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Imodules/cealign/src -Ibuild/generated -Icontrib/uiuc/plugins/molfile_plugin/src -Icontrib/mmtf-c -IlayerCTest -I/opt/homebrew/lib/python3.9/site-packages/numpy/core/include -I/opt/homebrew/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c -MMD layerCTest/Test.cpp -o build/temp.macosx-11-arm64-3.9/layerCTest/Test.o -Werror=return-type -Wunused-variable -Wno-switch -Wno-narrowing -Wno-char-subscripts -O3 -fno-strict-aliasing
10 warnings generated.
clang++ -I/opt/homebrew/opt/freetype/include -std=c++11 -D_PYMOL_LIBPNG -D_PYMOL_FREETYPE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -DMMTF_MSGPACK_USE_CPP11 -D_PYMOL_CTEST -D_PYMOL_OSX -D_PYMOL_NUMPY -Iinclude -Icontrib/uiuc/plugins/include -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Imodules/cealign/src -Ibuild/generated -Icontrib/uiuc/plugins/molfile_plugin/src -Icontrib/mmtf-c -IlayerCTest -I/opt/homebrew/lib/python3.9/site-packages/numpy/core/include -I/opt/homebrew/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c -MMD layer3/ExecutivePython.cpp -o build/temp.macosx-11-arm64-3.9/layer3/ExecutivePython.o -Werror=return-type -Wunused-variable -Wno-switch -Wno-narrowing -Wno-char-subscripts -O3 -fno-strict-aliasing
clang++ -I/opt/homebrew/opt/freetype/include -std=c++11 -D_PYMOL_LIBPNG -D_PYMOL_FREETYPE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -DMMTF_MSGPACK_USE_CPP11 -D_PYMOL_CTEST -D_PYMOL_OSX -D_PYMOL_NUMPY -Iinclude -Icontrib/uiuc/plugins/include -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Imodules/cealign/src -Ibuild/generated -Icontrib/uiuc/plugins/molfile_plugin/src -Icontrib/mmtf-c -IlayerCTest -I/opt/homebrew/lib/python3.9/site-packages/numpy/core/include -I/opt/homebrew/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c -MMD layer3/Selector.cpp -o build/temp.macosx-11-arm64-3.9/layer3/Selector.o -Werror=return-type -Wunused-variable -Wno-switch -Wno-narrowing -Wno-char-subscripts -O3 -fno-strict-aliasing
clang++ -I/opt/homebrew/opt/freetype/include -std=c++11 -D_PYMOL_LIBPNG -D_PYMOL_FREETYPE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -DMMTF_MSGPACK_USE_CPP11 -D_PYMOL_CTEST -D_PYMOL_OSX -D_PYMOL_NUMPY -Iinclude -Icontrib/uiuc/plugins/include -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Imodules/cealign/src -Ibuild/generated -Icontrib/uiuc/plugins/molfile_plugin/src -Icontrib/mmtf-c -IlayerCTest -I/opt/homebrew/lib/python3.9/site-packages/numpy/core/include -I/opt/homebrew/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c -MMD layer3/SelectorTmp.cpp -o build/temp.macosx-11-arm64-3.9/layer3/SelectorTmp.o -Werror=return-type -Wunused-variable -Wno-switch -Wno-narrowing -Wno-char-subscripts -O3 -fno-strict-aliasing
clang++ -I/opt/homebrew/opt/freetype/include -std=c++11 -D_PYMOL_LIBPNG -D_PYMOL_FREETYPE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -DMMTF_MSGPACK_USE_CPP11 -D_PYMOL_CTEST -D_PYMOL_OSX -D_PYMOL_NUMPY -Iinclude -Icontrib/uiuc/plugins/include -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Imodules/cealign/src -Ibuild/generated -Icontrib/uiuc/plugins/molfile_plugin/src -Icontrib/mmtf-c -IlayerCTest -I/opt/homebrew/lib/python3.9/site-packages/numpy/core/include -I/opt/homebrew/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c -MMD layerCTest/Test_Algorithm.cpp -o build/temp.macosx-11-arm64-3.9/layerCTest/Test_Algorithm.o -Werror=return-type -Wunused-variable -Wno-switch -Wno-narrowing -Wno-char-subscripts -O3 -fno-strict-aliasing
error: command '/opt/homebrew/Library/Homebrew/shims/mac/super/clang++' failed with exit code 1

Do not report this issue to Homebrew/brew or Homebrew/core!

- What you expected to happen

I can install pymol successfully if I add `arch -x86_64`, but I wish install it natively.

- Step-by-step reproduction instructions (by running `brew install` commands)

# brew doctor output
                                                                        
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/brew git origin remote found.
The current git origin is:
  https://mirrors.ustc.edu.cn/brew.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/opt/homebrew" remote set-url origin https://github.com/Homebrew/brew

Warning: Suspicious https://github.com/Homebrew/homebrew-core git origin remote found.
The current git origin is:
  https://mirrors.ustc.edu.cn/homebrew-core.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/opt/homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/bin/pkg-config
  /usr/local/bin/jemalloc-config
  /usr/local/bin/nf-config
  /usr/local/bin/freetype-config
  /usr/local/bin/libpng16-config
  /usr/local/bin/libpng-config
  /usr/local/bin/python3.9-config
  /usr/local/bin/python3-config
  /usr/local/bin/pcre-config
  /usr/local/bin/ncxx4-config
  /usr/local/bin/nc-config
  /usr/local/bin/sdl2-config
  /usr/local/bin/guile-config

Warning: gettext files detected at a system prefix.
These files can cause compilation and link failures, especially if they
are compiled with improper architectures. Consider removing these files:
  /opt/homebrew/lib/libgettextlib.dylib
  /opt/homebrew/lib/libintl.dylib
  /opt/homebrew/include/libintl.h
  /usr/local/lib/libgettextlib.dylib
  /usr/local/lib/libintl.dylib
  /usr/local/include/libintl.h

# brew config  output                                                  
HOMEBREW_VERSION: 3.0.1-122-gcdaf5cc
ORIGIN: https://mirrors.ustc.edu.cn/brew.git
HEAD: cdaf5cca165c3edfc63074f5cd6ca04234bb3ef4
Last commit: 23 hours ago
Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-core.git
Core tap HEAD: ee19f1c2b258bba32ca001ea723020b05bbd3193
Core tap last commit: 78 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Og4BUYJU9L/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
Rosetta 2: false

# Formula additions or changes

To get formulae added or changed in Brewsci/bio please file a [Pull Request](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md).

**Comment by YoshitakaMo** [comment] 2021-02-22 12:32
This issue is probably caused by a mistake of `CPPFLAGS`. According to your log, `-I/opt/homebrew/opt/freetype/include` was used, but it must be `-I/opt/homebrew/opt/freetype/include/freetype2`. The flags will be correctly set on macOS without M1 chip.

The PR https://github.com/brewsci/homebrew-bio/pull/1291 is my workaround.

**Comment by perrogg** [comment] 2021-02-23 05:39
> This issue is probably caused by a mistake of `CPPFLAGS`. According to your log, `-I/opt/homebrew/opt/freetype/include` was used, but it must be `-I/opt/homebrew/opt/freetype/include/freetype2`. The flags will be correctly set on macOS without M1 chip.
> 
> The PR #1291 is my workaround.

Thanks a lot. It works for me now.

**Comment by YoshitakaMo** [comment] 2021-02-23 18:56
PR https://github.com/brewsci/homebrew-bio/pull/1291 has been merged.

**Closed by YoshitakaMo** 2021-02-23 18:56 UTC
