### ISSUE TITLE
Reporting issue - brew upgrade

### ISSUE THREAD

**Issue by conra91** [brewsci/homebrew-bio#25] opened 2018-02-05 17:58 UTC
Hi,

Not sure if the place to report this but was just using brew upgrade for prokka and the following notice came up regarding the perl dependency.

```
==> Installing brewsci/science/prokka
Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/prokka.rb:13:in `<class:Prokka>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/prokka.rb:14:in `<class:Prokka>'
Please report this to the brewsci/science tap!
```

So, consider this me reporting!

**Comment by sjackman** [comment] 2018-02-05 22:57
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment] 2018-02-05 22:58
Thanks for the bug report, @conra91.

```
Please report this to the brewsci/science tap!
```
The correct repo to report this error is https://github.com/brewsci/homebrew-science

Duplicate of https://github.com/brewsci/homebrew-science/issues/14

**Closed** 2018-02-05 22:58 UTC
Labels: duplicate

**Comment by sjackman** [comment] 2018-02-06 00:42
I've fixed this issue just now.
